### ISSUE TITLE
网页中MathJax内嵌公式会自动翻译

### ISSUE THREAD

**Issue by zheng-gl** [windingwind/notranslate#1]
windingwind：
您好！
首先感谢您编写的《notranslate》软件，非常方便方便实现了网页中自动翻译公式混乱的问题。
向您提出一个我在使用中遇到的问题：网页可以不自动翻译“显示公式（通常编号的公式）”，但对于"内嵌公式(在段落中间的公式)"会自动翻译。这些公式好像都是MathJax v2.7.4编写的，如下图：

![问题](https://user-images.githubusercontent.com/45842041/78239464-4d001900-7510-11ea-832a-69fa5001b24c.jpg)
![原网页](https://user-images.githubusercontent.com/45842041/78240024-019a3a80-7511-11ea-8ee6-bf72de66a988.jpg)

期待您能解决这个问题，感谢您的辛苦付出。致敬！

**Comment by windingwind** [comment]
非常感谢您对这个本来仅仅是为了满足自己方便的小工具的使用。
方便的话可以提供一下出现问题的页面吗？我会将修正后的版本更新到GreasyFork。

**Comment by zheng-gl** [comment]
https://ieeexplore.ieee.org/document/1041400
这个是IEEE网站论文，我用的学校IP打开，不确定您是否可以打开

**Comment by windingwind** [comment]
![image](https://user-images.githubusercontent.com/33902321/78250502-85a8ee00-7522-11ea-9a70-3d8573e2fb9a.png)
我这边已经进行了版本的更新，确认可以使用，可以在https://greasyfork.org/zh-CN/scripts/396736-notranslate-prevent-translating-snippets-and-formulas 进行脚本更新。
如果确认没有问题，我会将这个issue关闭。非常感谢您的建议！

**Comment by zheng-gl** [comment]
没问题了，超好用
